const { supabase, session, membership, projectId, role } = window.AGIT;
const app = document.getElementById('app');
const navHost = document.getElementById('nav');
const modal = document.getElementById('modalBackdrop');
const modalBody = document.getElementById('modalBody');
const modalFoot = document.getElementById('modalFoot');
const roleNames = { owner:'Руководитель', manager:'Координатор', finance:'Финансы', media:'Медиа', organizer:'Организатор', mentor:'Наставник', viewer:'Просмотр' };
const pages = [
  ['dashboard','⌂','Панель'],['calendar','▣','Календарь'],['participants','♟','Участники'],['media','◉','Публикации'],
  ['budget','₽','Бюджет'],['documents','▤','Документы'],['quality','◇','Качество'],['partners','◎','Партнёры'],
  ['team','♣','Команда'],['report','✓','Отчётность']
];
const can = {
  manage: ['owner','manager'].includes(role), event: ['owner','manager','organizer'].includes(role),
  participant: ['owner','manager','organizer'].includes(role), media: ['owner','manager','media'].includes(role),
  finance: ['owner','finance'].includes(role), docs: ['owner','manager','finance','media','organizer'].includes(role),
  quality: ['owner','manager','organizer'].includes(role), owner: role === 'owner'
};
let page = location.hash.slice(1) || 'dashboard';
let project, cache = {};

const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money = v => new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB',maximumFractionDigits:0}).format(Number(v||0));
const date = v => v ? new Date(`${v}T00:00:00`).toLocaleDateString('ru-RU') : '—';
const pct = (a,b) => b ? Math.min(100, Math.round(Number(a||0)/Number(b)*100)) : 0;
const iso = () => new Date().toISOString().slice(0,10);
const toast = (text,type='success') => { const n=document.createElement('div'); n.className=`toast ${type}`; n.textContent=text; document.getElementById('toastStack').append(n); setTimeout(()=>n.remove(),3500); };
function sync(text,status='ok'){ const box=document.querySelector('.sync-state'); if(box){box.dataset.status=status; box.lastElementChild.textContent=text;} }
function statusClass(v=''){ const s=v.toLowerCase(); return s.includes('заверш')||s.includes('готов')||s.includes('оплачен')?'status-green':s.includes('работ')||s.includes('подготов')||s.includes('заказ')?'status-blue':s.includes('проср')||s.includes('отклон')?'status-red':'status-gray'; }
function field(name,label,value='',type='text',extra=''){ return `<div class="form-group"><label>${esc(label)}</label><input name="${esc(name)}" type="${type}" value="${esc(value)}" ${extra}></div>`; }
function textarea(name,label,value=''){ return `<div class="form-group full"><label>${esc(label)}</label><textarea name="${esc(name)}">${esc(value)}</textarea></div>`; }
function select(name,label,value,opts){ return `<div class="form-group"><label>${esc(label)}</label><select name="${esc(name)}">${opts.map(o=>`<option ${o===value?'selected':''}>${esc(o)}</option>`).join('')}</select></div>`; }
function openModal(title, html, onSave, saveText='Сохранить'){
  document.getElementById('modalTitle').textContent=title; modalBody.innerHTML=`<form id="modalForm" class="form-grid">${html}</form>`;
  modalFoot.innerHTML=`<button class="btn btn-secondary" data-close>Отмена</button><button class="btn btn-primary" id="modalSave">${saveText}</button>`;
  modal.classList.remove('hidden'); modal.querySelector('[data-close]').onclick=closeModal;
  document.getElementById('modalSave').onclick=async()=>{ const btn=document.getElementById('modalSave'); btn.disabled=true; try{ await onSave(new FormData(document.getElementById('modalForm'))); closeModal(); await loadPage(); toast('Сохранено'); }catch(e){ console.error(e); toast(e.message||'Ошибка','error'); }finally{btn.disabled=false;} };
}
function closeModal(){ modal.classList.add('hidden'); modalBody.innerHTML=''; modalFoot.innerHTML=''; }
modal.addEventListener('click',e=>{ if(e.target===modal||e.target.closest('[data-action="close-modal"]')) closeModal(); });

async function query(table, select='*', options={}){
  let q=supabase.from(table).select(select);
  if(options.project!==false) q=q.eq('project_id',projectId);
  if(options.order) q=q.order(options.order,{ascending:options.asc!==false});
  const {data,error}=await q; if(error) throw error; return data||[];
}
async function loadBase(){
  const {data,error}=await supabase.from('projects').select('*').eq('id',projectId).single(); if(error) throw error; project=data;
  document.getElementById('projectDates').innerHTML=`<strong>${esc(project.name)}</strong>${date(project.start_date)} — ${date(project.end_date)}`;
}
async function loadAll(){
  const promises=[
    query('events','*',{order:'sort_order'}), query('publications','*',{order:'published_at',asc:false}), query('budget_items','*',{order:'code'}),
    query('project_documents','*',{order:'created_at',asc:false}), query('quality_metrics','*',{order:'code'}), query('partners','*',{order:'name'}),
    query('risks','*',{order:'created_at'}), query('report_requirements','*',{order:'appendix_number'}), query('report_sections','*',{order:'section_key'})
  ];
  if(can.participant) promises.push(query('participants','*',{order:'full_name'}),query('participant_attendance','*,participants(*),events(id,name,due_date,actual_date)',{order:'created_at'}));
  else promises.push(Promise.resolve([]),Promise.resolve([]));
  if(can.manage||can.owner) promises.push(query('project_members','*,profiles:user_id(full_name,email)',{order:'created_at'})); else promises.push(Promise.resolve([]));
  [cache.events,cache.publications,cache.budget,cache.documents,cache.quality,cache.partners,cache.risks,cache.requirements,cache.sections,cache.participants,cache.attendance,cache.members]=await Promise.all(promises);
  const {data:kpis,error}=await supabase.rpc('get_project_kpis',{p_project_id:projectId}); if(!error) cache.kpis=kpis?.[0];
}
function renderNav(){ navHost.innerHTML=pages.map(([id,icon,label])=>`<button data-page="${id}" class="${page===id?'active':''}"><span class="nav-icon">${icon}</span><span class="nav-label">${label}</span></button>`).join(''); navHost.onclick=e=>{const b=e.target.closest('[data-page]');if(b){location.hash=b.dataset.page;}}; }
function head(title,subtitle,actions=''){ document.getElementById('pageTitle').textContent=title; document.getElementById('pageEyebrow').textContent='Управление проектом'; return `<div class="page-intro"><div><h2>${esc(title)}</h2><p>${esc(subtitle)}</p></div><div class="page-actions">${actions}</div></div>`; }
function kpi(label,val,plan,icon,cls=''){return `<div class="card kpi-card"><div class="kpi-top"><span class="kpi-label">${label}</span><span class="kpi-icon">${icon}</span></div><div class="kpi-number">${val}</div><div class="kpi-plan">план: ${plan}</div><div class="progress ${cls}"><span style="width:${pct(val,plan)}%"></span></div></div>`;}
function smartAlerts(){
  const alerts=[]; const now=new Date();
  cache.events.forEach(e=>{if(['completed','cancelled'].includes(e.status))return;const d=Math.ceil((new Date(`${e.due_date}T23:59:59`)-now)/86400000);if(d<0)alerts.push(['critical',`Просрочено: ${e.name}`,`Срок был ${date(e.due_date)}. Зафиксируйте результат или причину переноса.`]);else if(d<=30)alerts.push(['warning',`До срока ${d} дней: ${e.name}`,`Проверьте списки, фото, публикации и итоговую справку.`]);});
  const pubs=cache.publications.length;
  if(pubs<project.plan_publications)alerts.push(['info','Медиаплан требует внимания',`Осталось подготовить ${project.plan_publications-pubs} публикаций и подтвердить просмотры скриншотами.`]);
  const paid=cache.budget.filter(x=>['paid','closed'].includes(x.status));
  paid.forEach(b=>{const docs=cache.documents.filter(d=>d.category==='finance'&&d.description?.includes(b.code));if(!docs.length)alerts.push(['critical',`Нет доказательств по ${b.code}`,`Позиция «${b.name}» оплачена, но в общем реестре не найден финансовый комплект.`]);});
  return alerts.slice(0,8);
}
function renderDashboard(){
  const k=cache.kpis||{}; const alerts=smartAlerts(); const next=cache.events.filter(e=>!['completed','cancelled'].includes(e.status)).sort((a,b)=>a.due_date.localeCompare(b.due_date)).slice(0,5);
  app.innerHTML=head('Панель управления','Свод план–факт, ближайшие сроки и подсказки для команды.')+
  `<div class="grid grid-4">${kpi('Мероприятия',k.actual_events||0,project.plan_events,'▣')}${kpi('Участники 14–35',k.actual_unique_participants||0,project.plan_unique_participants,'♟','green')}${kpi('Публикации',k.actual_publications||0,project.plan_publications,'◉','gold')}${kpi('Просмотры',k.actual_views||0,project.plan_views,'◎','blue')}</div>
  <div class="grid grid-main" style="margin-top:16px"><section class="card"><div class="card-head"><div><h3>Умные подсказки</h3><p>Сформированы по срокам, показателям и комплектности доказательств.</p></div></div><div class="card-body alert-list">${alerts.length?alerts.map(a=>`<div class="alert alert-${a[0]}"><span class="alert-icon">${a[0]==='critical'?'!':a[0]==='warning'?'⌛':'i'}</span><div><strong>${esc(a[1])}</strong><p>${esc(a[2])}</p></div></div>`).join(''):'<div class="alert alert-good"><span class="alert-icon">✓</span><div><strong>Критических сигналов нет</strong><p>Продолжайте своевременно вносить фактические данные и доказательства.</p></div></div>'}</div></section>
  <section class="card"><div class="card-head"><div><h3>Ближайшие этапы</h3><p>Следующие сроки календарного плана.</p></div></div><div class="card-body timeline">${next.map(e=>`<div class="timeline-item"><div class="timeline-date">${date(e.due_date)}</div><div class="timeline-title">${esc(e.name)}</div><div class="timeline-meta">${esc(e.location||'')} · ${esc(e.status)}</div></div>`).join('')||'<div class="empty">Все этапы завершены</div>'}</div></section></div>
  <div class="grid grid-3" style="margin-top:16px"><div class="card card-pad"><div class="stat-pair"><strong>${money(k.actual_budget||0)}</strong><span>из ${money(project.plan_budget)}</span></div><div class="progress"><span style="width:${pct(k.actual_budget,project.plan_budget)}%"></span></div><p class="subtle">Фактически освоено по смете</p></div><div class="card card-pad"><div class="stat-pair"><strong>${k.overdue_events||0}</strong><span>просроченных этапов</span></div><p class="subtle">Незавершённые строки календарного плана с истёкшим сроком</p></div><div class="card card-pad"><div class="stat-pair"><strong>${cache.requirements.filter(x=>x.status==='verified').length}</strong><span>из ${cache.requirements.length}</span></div><p class="subtle">Требований итогового отчёта проверено</p></div></div>`;
}
function renderCalendar(){
  app.innerHTML=head('Календарный план','Каждая строка календаря считается одним отчётным мероприятием.',can.event?'<button class="btn btn-primary" data-new-event>+ Мероприятие</button>':'')+
  `<div class="event-grid">${cache.events.map(e=>`<article class="card event-card"><div class="event-code">${esc(e.code)}</div><div class="event-title">${esc(e.name)}</div><div class="event-meta"><span>Срок<br><strong>${date(e.due_date)}</strong></span><span>Место<br><strong>${esc(e.location||'—')}</strong></span><span>Участники<br><strong>${e.actual_unique_participants||0}/${e.plan_unique_participants||0}</strong></span><span>Медиа<br><strong>${e.actual_publications||0}/${e.plan_publications||0}</strong></span></div><div class="progress"><span style="width:${pct(e.actual_unique_participants,e.plan_unique_participants)}%"></span></div><div class="event-footer"><span class="status ${statusClass(e.status)}">${esc(e.status)}</span>${can.event?`<button class="mini-btn" data-edit-event="${e.id}">Открыть</button>`:''}</div></article>`).join('')}</div>`;
  app.querySelector('[data-new-event]')?.addEventListener('click',()=>editEvent()); app.querySelectorAll('[data-edit-event]').forEach(b=>b.onclick=()=>editEvent(cache.events.find(x=>x.id===b.dataset.editEvent)));
}
function editEvent(e={}){ openModal(e.id?'Карточка мероприятия':'Новое мероприятие',
  field('code','Код',e.code||'')+field('name','Название',e.name||'')+field('due_date','Крайний срок',e.due_date||'', 'date')+field('actual_date','Фактическая дата',e.actual_date||'','date')+field('location','Место',e.location||'')+select('status','Статус',e.status||'planned',['planned','preparing','in_progress','completed','cancelled'])+field('actual_unique_participants','Уникальные участники',e.actual_unique_participants||0,'number')+field('actual_repeat_participants','Повторные участия',e.actual_repeat_participants||0,'number')+field('actual_publications','Публикации',e.actual_publications||0,'number')+field('actual_views','Просмотры',e.actual_views||0,'number')+textarea('result_summary','Фактический результат',e.result_summary||'')+textarea('problems','Проблемы и решения',e.problems||''),
  async fd=>{const v=Object.fromEntries(fd);['actual_unique_participants','actual_repeat_participants','actual_publications','actual_views'].forEach(k=>v[k]=Number(v[k]||0));v.project_id=projectId;if(e.id){const{error}=await supabase.from('events').update(v).eq('id',e.id);if(error)throw error;}else{v.sort_order=cache.events.length+1;const{error}=await supabase.from('events').insert(v);if(error)throw error;}});
}
function renderParticipants(){
  if(!can.participant){app.innerHTML=head('Участники','Персональные данные доступны руководителю, координатору и организаторам.')+'<div class="callout"><strong>Ограничение роли</strong><p>Для вашей роли доступен только агрегированный показатель на главной панели.</p></div>';return;}
  const eligible=cache.participants.filter(p=>p.birth_date&&ageAt(p.birth_date,project.end_date)>=14&&ageAt(p.birth_date,project.end_date)<=35).length;
  app.innerHTML=head('Участники',`Единый реестр: ${cache.participants.length}; предварительно соответствуют возрасту 14–35: ${eligible}.`,'<button class="btn btn-primary" data-add-participant>+ Участник</button>')+
  `<div class="table-wrap"><table><thead><tr><th>ФИО</th><th>Дата рождения</th><th>Возраст</th><th>Организация</th><th>Контакт</th><th>Согласия</th><th></th></tr></thead><tbody>${cache.participants.map(p=>`<tr><td><strong>${esc(p.full_name)}</strong></td><td>${date(p.birth_date)}</td><td>${p.birth_date?ageAt(p.birth_date,project.end_date):'—'}</td><td>${esc(p.organization||'')}</td><td>${esc(p.contact_value||'')}</td><td>${p.consent_personal_data?'ПД ✓':'ПД —'} · ${p.consent_media?'Фото ✓':'Фото —'}</td><td><button class="mini-btn" data-participant="${p.id}">Изменить</button> <button class="mini-btn" data-attend="${p.id}">Участие</button></td></tr>`).join('')}</tbody></table></div>`;
  app.querySelector('[data-add-participant]').onclick=()=>editParticipant(); app.querySelectorAll('[data-participant]').forEach(b=>b.onclick=()=>editParticipant(cache.participants.find(x=>x.id===b.dataset.participant))); app.querySelectorAll('[data-attend]').forEach(b=>b.onclick=()=>addAttendance(b.dataset.attend));
}
function ageAt(birth,on){let b=new Date(birth),d=new Date(on);let a=d.getFullYear()-b.getFullYear();if(d.getMonth()<b.getMonth()||(d.getMonth()===b.getMonth()&&d.getDate()<b.getDate()))a--;return a;}
function editParticipant(p={}){openModal(p.id?'Участник':'Новый участник',field('full_name','ФИО',p.full_name||'')+field('birth_date','Дата рождения',p.birth_date||'','date')+field('organization','Организация',p.organization||'')+field('municipality','Муниципалитет',p.municipality||'Кемский муниципальный округ')+field('contact_value','Телефон / e-mail / ссылка',p.contact_value||'')+`<div class="form-group"><label><input style="width:auto" type="checkbox" name="consent_personal_data" ${p.consent_personal_data?'checked':''}> Согласие на ПД</label></div><div class="form-group"><label><input style="width:auto" type="checkbox" name="consent_media" ${p.consent_media?'checked':''}> Согласие на фото/видео</label></div>`+textarea('notes','Примечание',p.notes||''),async fd=>{const v=Object.fromEntries(fd);v.project_id=projectId;v.consent_personal_data=fd.has('consent_personal_data');v.consent_media=fd.has('consent_media');const r=p.id?await supabase.from('participants').update(v).eq('id',p.id):await supabase.from('participants').insert(v);if(r.error)throw r.error;});}
function addAttendance(participantId){openModal('Добавить участие',`<div class="form-group full"><label>Мероприятие</label><select name="event_id">${cache.events.map(e=>`<option value="${e.id}">${esc(e.code)} — ${esc(e.name)}</option>`).join('')}</select></div>`+field('attended_at','Дата и время',new Date().toISOString().slice(0,16),'datetime-local')+field('source','Источник подтверждения','Именной список')+textarea('notes','Примечание',''),async fd=>{const v=Object.fromEntries(fd);v.project_id=projectId;v.participant_id=participantId;v.attended_at=new Date(v.attended_at).toISOString();const{error}=await supabase.from('participant_attendance').upsert(v,{onConflict:'event_id,participant_id'});if(error)throw error;});}
function renderMedia(){
  const views=cache.publications.reduce((s,x)=>s+Number(x.views||0),0); app.innerHTML=head('Публикации',`${cache.publications.length}/${project.plan_publications} публикаций; ${views.toLocaleString('ru-RU')}/${Number(project.plan_views).toLocaleString('ru-RU')} просмотров.`,can.media?'<button class="btn btn-primary" data-add-publication>+ Публикация</button>':'')+
  `<div class="table-wrap"><table><thead><tr><th>Дата</th><th>Площадка и заголовок</th><th>Просмотры</th><th>Проверки</th><th>Ссылка</th><th></th></tr></thead><tbody>${cache.publications.map(p=>`<tr><td>${p.published_at?new Date(p.published_at).toLocaleDateString('ru-RU'):'—'}</td><td><strong>${esc(p.title||'Без названия')}</strong><br><span class="subtle">${esc(p.platform||p.media_name||'')}</span></td><td class="number">${Number(p.views||0).toLocaleString('ru-RU')}</td><td>${p.screenshot_path?'Скрин ✓':'Скрин —'} · ${p.grant_mention||p.hashtags_present?'Маркировка ✓':'Маркировка —'}</td><td><a class="link" href="${esc(p.url)}" target="_blank">Открыть</a></td><td>${can.media?`<button class="mini-btn" data-publication="${p.id}">Изменить</button>`:''}</td></tr>`).join('')}</tbody></table></div>`;
  app.querySelector('[data-add-publication]')?.addEventListener('click',()=>editPublication()); app.querySelectorAll('[data-publication]').forEach(b=>b.onclick=()=>editPublication(cache.publications.find(x=>x.id===b.dataset.publication)));
}
function editPublication(p={}){openModal(p.id?'Публикация':'Новая публикация',field('title','Заголовок',p.title||'')+field('platform','Площадка',p.platform||'ВКонтакте')+field('published_at','Дата',p.published_at?.slice(0,10)||iso(),'date')+field('views','Просмотры',p.views||0,'number')+`<div class="form-group full"><label>Активная ссылка</label><input name="url" type="url" value="${esc(p.url||'')}" required></div><div class="form-group"><label><input style="width:auto" type="checkbox" name="hashtags_present" ${p.hashtags_present?'checked':''}> Хештеги видны</label></div><div class="form-group"><label><input style="width:auto" type="checkbox" name="grant_mention" ${p.grant_mention?'checked':''}> Поддержка указана</label></div><div class="form-group full"><label>Скриншот<input name="screenshot" type="file" accept="image/*,.pdf"></label></div>`+textarea('verification_notes','Примечание',p.verification_notes||''),async fd=>{const file=fd.get('screenshot');const v={project_id:projectId,title:fd.get('title'),platform:fd.get('platform'),published_at:new Date(fd.get('published_at')).toISOString(),views:Number(fd.get('views')||0),url:fd.get('url'),hashtags_present:fd.has('hashtags_present'),grant_mention:fd.has('grant_mention'),verification_notes:fd.get('verification_notes')};if(file&&file.size){const path=`${projectId}/publication/${p.id||crypto.randomUUID()}/${Date.now()}-${file.name.replace(/[^\wа-яё.()-]+/gi,'_')}`;const up=await supabase.storage.from('media-screenshots').upload(path,file);if(up.error)throw up.error;v.screenshot_path=path;}const r=p.id?await supabase.from('publications').update(v).eq('id',p.id):await supabase.from('publications').insert(v);if(r.error)throw r.error;});}
function renderBudget(){
  const actual=cache.budget.reduce((s,x)=>s+Number(x.actual_amount||0),0); app.innerHTML=head('Бюджет',`${money(actual)} освоено из ${money(project.plan_budget)}. Плановые суммы защищены от изменения.`,can.finance?'<button class="btn btn-secondary" data-finance-doc>+ Финансовый документ</button>':'')+
  `<div class="table-wrap"><table><thead><tr><th>Код</th><th>Статья</th><th>План</th><th>Факт</th><th>Статус</th><th>Поставщик</th><th></th></tr></thead><tbody>${cache.budget.map(b=>`<tr><td>${esc(b.code)}</td><td><strong>${esc(b.name)}</strong><br><span class="subtle">${esc(b.category)}</span></td><td class="number">${money(b.planned_amount)}</td><td class="number">${money(b.actual_amount)}</td><td><span class="status ${statusClass(b.status)}">${esc(b.status)}</span></td><td>${esc(b.supplier||'')}</td><td>${can.finance?`<button class="mini-btn" data-budget="${b.id}">Факт</button>`:''}</td></tr>`).join('')}</tbody></table></div>`;
  app.querySelectorAll('[data-budget]').forEach(b=>b.onclick=()=>editBudget(cache.budget.find(x=>x.id===b.dataset.budget)));app.querySelector('[data-finance-doc]')?.addEventListener('click',()=>addFinanceDocument());
}
function editBudget(b){openModal(`Факт по ${b.code}`,field('actual_amount','Фактическая сумма',b.actual_amount||0,'number','step="0.01"')+select('status','Статус',b.status,['planned','contracting','ordered','paid','closed'])+field('supplier','Поставщик',b.supplier||'')+field('contract_number','Номер договора',b.contract_number||'')+field('contract_date','Дата договора',b.contract_date||'','date')+field('payment_date','Дата оплаты',b.payment_date||'','date')+textarea('notes','Примечание',b.notes||''),async fd=>{const v=Object.fromEntries(fd);v.actual_amount=Number(v.actual_amount||0);const{error}=await supabase.from('budget_items').update(v).eq('id',b.id);if(error)throw error;});}
function addFinanceDocument(){openModal('Финансовый документ',`<div class="form-group full"><label>Позиция сметы</label><select name="budget_item_id">${cache.budget.map(b=>`<option value="${b.id}">${b.code} — ${esc(b.name)}</option>`).join('')}</select></div>`+select('document_type','Тип','Договор',['Договор','Спецификация','Счёт','Акт','УПД','Платёжное поручение','Чек НПД','Иное'])+field('document_number','Номер','')+field('document_date','Дата',iso(),'date')+field('amount','Сумма',0,'number','step="0.01"')+`<div class="form-group full"><label>Файл<input name="file" type="file" required></label></div>`+textarea('notes','Примечание',''),async fd=>{const file=fd.get('file');const item=cache.budget.find(x=>x.id===fd.get('budget_item_id'));const path=`${projectId}/${item.code}/${Date.now()}-${file.name.replace(/[^\wа-яё.()-]+/gi,'_')}`;const up=await supabase.storage.from('finance').upload(path,file);if(up.error)throw up.error;const{error}=await supabase.from('financial_documents').insert({project_id:projectId,budget_item_id:item.id,document_type:fd.get('document_type'),document_number:fd.get('document_number'),document_date:fd.get('document_date'),amount:Number(fd.get('amount')||0),file_path:path,status:'uploaded',uploaded_by:session.user.id,notes:fd.get('notes')});if(error)throw error;});}
function renderDocuments(){app.innerHTML=head('Подтверждающие документы','Храните письма, списки, программы, фотоархивы, анкеты и итоговые справки.',can.docs?'<button class="btn btn-primary" data-add-doc>+ Документ</button>':'')+`<div class="table-wrap"><table><thead><tr><th>Дата</th><th>Категория</th><th>Название</th><th>Мероприятие</th><th>Статус</th><th>Файл/ссылка</th></tr></thead><tbody>${cache.documents.map(d=>`<tr><td>${date(d.document_date)}</td><td>${esc(d.category)}</td><td><strong>${esc(d.title)}</strong><br><span class="subtle">${esc(d.description||'')}</span></td><td>${esc(cache.events.find(e=>e.id===d.event_id)?.code||'Общий')}</td><td><span class="status ${statusClass(d.status)}">${esc(d.status)}</span></td><td>${d.file_path?`<button class="mini-btn" data-download="${esc(d.file_path)}">Скачать</button>`:d.external_url?`<a class="link" href="${esc(d.external_url)}" target="_blank">Открыть</a>`:'—'}</td></tr>`).join('')}</tbody></table></div>`;app.querySelector('[data-add-doc]')?.addEventListener('click',()=>addDocument());app.querySelectorAll('[data-download]').forEach(b=>b.onclick=()=>download(b.dataset.download,'project-documents'));}
function addDocument(){openModal('Добавить документ',select('category','Категория','event',['event','participants','media','report','partner','other'])+`<div class="form-group"><label>Мероприятие</label><select name="event_id"><option value="">Общий документ</option>${cache.events.map(e=>`<option value="${e.id}">${e.code} — ${esc(e.name)}</option>`).join('')}</select></div>`+field('title','Название','')+field('document_date','Дата',iso(),'date')+field('external_url','Внешняя ссылка','','url')+`<div class="form-group full"><label>Файл<input name="file" type="file"></label></div>`+textarea('description','Описание',''),async fd=>{const file=fd.get('file');const v={project_id:projectId,category:fd.get('category'),event_id:fd.get('event_id')||null,title:fd.get('title'),document_date:fd.get('document_date'),external_url:fd.get('external_url')||null,description:fd.get('description'),status:'uploaded',uploaded_by:session.user.id};if(file&&file.size){const path=`${projectId}/${v.event_id||'general'}/${Date.now()}-${file.name.replace(/[^\wа-яё.()-]+/gi,'_')}`;const up=await supabase.storage.from('project-documents').upload(path,file);if(up.error)throw up.error;v.file_path=path;}const{error}=await supabase.from('project_documents').insert(v);if(error)throw error;});}
async function download(path,bucket){const{data,error}=await supabase.storage.from(bucket).download(path);if(error)return toast(error.message,'error');const a=document.createElement('a');a.href=URL.createObjectURL(data);a.download=path.split('/').pop();a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function renderQuality(){app.innerHTML=head('Качественные результаты','Фиксируйте методику, план и фактический социальный эффект.')+`<div class="grid grid-2">${cache.quality.map(q=>`<div class="card card-pad"><div class="eyebrow">${esc(q.code)}</div><h3>${esc(q.name)}</h3><p class="subtle">${esc(q.description||'')}</p><div class="stat-pair"><strong>${q.actual_value??'—'} ${esc(q.unit)}</strong><span>план ${q.planned_value??'—'}</span></div>${can.quality?`<button class="btn btn-secondary" data-quality="${q.id}" style="margin-top:12px">Внести факт</button>`:''}</div>`).join('')}</div>`;app.querySelectorAll('[data-quality]').forEach(b=>b.onclick=()=>editQuality(cache.quality.find(x=>x.id===b.dataset.quality)));}
function editQuality(q){openModal(q.name,field('actual_value','Фактическое значение',q.actual_value??'','number','step="0.01"')+textarea('measurement_method','Методика',q.measurement_method||'')+textarea('notes','Комментарий',q.notes||''),async fd=>{const v=Object.fromEntries(fd);v.actual_value=v.actual_value===''?null:Number(v.actual_value);const{error}=await supabase.from('quality_metrics').update(v).eq('id',q.id);if(error)throw error;});}
function renderPartners(){app.innerHTML=head('Партнёры и риски','Поддержка партнёров и управленческие риски проекта.',can.manage?'<button class="btn btn-primary" data-add-partner>+ Партнёр</button>':'')+`<div class="grid grid-2"><section class="card"><div class="card-head"><h3>Партнёры</h3></div><div class="card-body">${cache.partners.map(p=>`<div class="metric-row"><strong>${esc(p.name)}</strong><span>${esc(p.support_type||'')}</span><span>${money(p.actual_amount||p.planned_amount||0)}</span><span class="metric-note">${esc(p.support_description||'')}</span></div>`).join('')}</div></section><section class="card"><div class="card-head"><h3>Риски</h3></div><div class="card-body alert-list">${cache.risks.map(r=>`<div class="alert alert-${r.impact==='critical'?'critical':r.impact==='high'?'warning':'info'}"><span class="alert-icon">!</span><div><strong>${esc(r.title)}</strong><p>${esc(r.mitigation||r.description||'Не определена мера реагирования')}</p></div></div>`).join('')}</div></section></div>`;app.querySelector('[data-add-partner]')?.addEventListener('click',()=>addPartner());}
function addPartner(){openModal('Новый партнёр',field('name','Название','')+field('support_type','Тип поддержки','Организационная')+field('planned_amount','Плановая оценка',0,'number')+field('contact_person','Контактное лицо','')+field('contact_details','Контакты','')+textarea('support_description','Описание поддержки',''),async fd=>{const v=Object.fromEntries(fd);v.project_id=projectId;v.planned_amount=Number(v.planned_amount||0);const{error}=await supabase.from('partners').insert(v);if(error)throw error;});}
function renderTeam(){
  const actions=can.owner?'<button class="btn btn-primary" data-add-member>+ Добавить зарегистрированного</button>':'';app.innerHTML=head('Команда',`Ваша роль: ${roleNames[role]||role}.`,actions)+`<div class="grid grid-3">${cache.members.length?cache.members.map(m=>`<div class="card card-pad"><div class="eyebrow">${roleNames[m.role]||m.role}</div><h3>${esc(m.profiles?.full_name||m.invited_email||'Участник')}</h3><p class="subtle">${esc(m.profiles?.email||m.invited_email||'')}</p><span class="status ${statusClass(m.status)}">${esc(m.status)}</span></div>`).join(''):`<div class="callout"><strong>Список команды</strong><p>Полный список доступен руководителю и координатору после обновления страницы.</p></div>`}</div>`;app.querySelector('[data-add-member]')?.addEventListener('click',()=>addMember());}
function addMember(){openModal('Добавить в команду',field('email','E-mail зарегистрированного пользователя','','email')+`<div class="form-group"><label>Роль</label><select name="role">${['manager','finance','media','organizer','mentor','viewer'].map(r=>`<option value="${r}">${roleNames[r]}</option>`).join('')}</select></div>`,async fd=>{const{error}=await supabase.rpc('add_existing_project_member',{p_project_id:projectId,p_email:fd.get('email'),p_role:fd.get('role')});if(error)throw error;});}
function renderReport(){const verified=cache.requirements.filter(x=>x.status==='verified').length;app.innerHTML=head('Итоговая отчётность',`Готово ${verified} из ${cache.requirements.length} контрольных требований.`)+`<div class="grid grid-main"><section class="card"><div class="card-head"><div><h3>Приложения и доказательства</h3><p>Плановые показатели в отчёте не уменьшаются.</p></div></div><div>${cache.requirements.map(r=>`<div class="report-step"><div class="step-num">${r.appendix_number||'✓'}</div><div><h4>${esc(r.title)}</h4><p>${esc(r.description||'')}</p></div><div><span class="status ${statusClass(r.status)}">${esc(r.status)}</span>${can.manage?`<button class="mini-btn" data-req="${r.id}" style="margin-top:8px">Статус</button>`:''}</div></div>`).join('')}</div></section><section class="card"><div class="card-head"><h3>Черновики Приложения 3</h3></div><div class="card-body">${cache.sections.map(s=>`<div style="margin-bottom:14px"><strong>${esc(s.title)}</strong><p class="subtle">${esc((s.content||'Не заполнено').slice(0,180))}</p>${can.manage?`<button class="mini-btn" data-section="${s.id}">Редактировать</button>`:''}</div>`).join('')}</div></section></div>`;app.querySelectorAll('[data-req]').forEach(b=>b.onclick=()=>editRequirement(cache.requirements.find(x=>x.id===b.dataset.req)));app.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>editSection(cache.sections.find(x=>x.id===b.dataset.section)));}
function editRequirement(r){openModal(r.title,select('status','Статус',r.status,['missing','draft','uploaded','verified','rejected'])+field('due_date','Срок',r.due_date||'','date')+textarea('notes','Комментарий',r.notes||''),async fd=>{const{error}=await supabase.from('report_requirements').update(Object.fromEntries(fd)).eq('id',r.id);if(error)throw error;});}
function editSection(s){openModal(s.title,textarea('content','Текст',s.content||''),async fd=>{const{error}=await supabase.from('report_sections').update({content:fd.get('content'),status:'draft',updated_by:session.user.id}).eq('id',s.id);if(error)throw error;});}
async function loadPage(){sync('Загружаем данные…','busy');await loadAll();renderNav();({dashboard:renderDashboard,calendar:renderCalendar,participants:renderParticipants,media:renderMedia,budget:renderBudget,documents:renderDocuments,quality:renderQuality,partners:renderPartners,team:renderTeam,report:renderReport}[page]||renderDashboard)();sync('Общая база подключена','ok');}
function userMenu(){const host=document.querySelector('.topbar-actions');const box=document.createElement('div');box.className='user-menu';box.innerHTML=`<div><strong>${esc(session.user.user_metadata?.full_name||session.user.email)}</strong><span>${roleNames[role]||role}</span></div><button class="btn btn-secondary" id="signOut">Выйти</button>`;host.prepend(box);document.getElementById('signOut').onclick=()=>supabase.auth.signOut();}
window.addEventListener('hashchange',()=>{page=location.hash.slice(1)||'dashboard';loadPage().catch(e=>{console.error(e);toast(e.message,'error')});});
document.getElementById('menuButton').onclick=()=>document.getElementById('sidebar').classList.toggle('open');document.querySelector('[data-action="backup"]').onclick=async()=>{await loadAll();const blob=new Blob([JSON.stringify({project,cache,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`agitbrigada-backup-${iso()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
await loadBase();userMenu();await loadPage();
const channel=supabase.channel(`agit-${projectId}`).on('postgres_changes',{event:'*',schema:'public'},payload=>{if(payload.new?.project_id===projectId||payload.old?.project_id===projectId){clearTimeout(window.__agitReload);window.__agitReload=setTimeout(()=>loadPage().catch(console.error),500);}}).subscribe();
window.addEventListener('beforeunload',()=>supabase.removeChannel(channel));
